[pytest]
pythonpath = .
norecursedirs = temp .venv .venv_cache .git __pycache__
addopts = -m "not integration"
markers =
    integration: mark test as requiring live Prometheus stack on localhost:9090
